from sklearn.model_selection import train_test_split
import numpy as np
import os, fnmatch
import random

dataDir = "/u/cs401/A3/data/"


class theta:
    def __init__(self, name, M=8, d=13):
        """
        Class holding model parameters.
        Use the `reset_parameter` functions below to
        initialize and update model parameters during training.
        """
        self.name = name
        self._M = M
        self._d = d
        self.omega = np.zeros((M, 1))
        self.mu = np.zeros((M, d))
        self.Sigma = np.zeros((M, d))

    def precomputedForM(self, m):
        """
        Put the precomputedforM for given `m` computation here
        This is a function of `self.mu` and `self.Sigma`
        This should output a float or equivalent (array of size [1] etc.)
        NOTE: use this in `log_b_m_x` below
        """

        return -0.5 * (self._d * np.log(2 * np.pi) + np.sum(np.log(self.Sigma[m])))



    def reset_omega(self, omega):
        """
        Resets omega.

        Parameters
        ----------
        omega : probability of an observation generated by certain component,
                should be of shape [M, 1] or [M]

        Returns
        -------
        N/A, resets self.omega to given omega
        """
        omega = np.asarray(omega)
        assert omega.size == self._M, "`omega` must contain M elements"
        self.omega = omega.reshape(self._M, 1)

    def reset_mu(self, mu):
        """
        Resets mu.

        Parameters
        ----------
        mu : mean for the M components,
             should be of shape [M, d]

        Returns
        -------
        N/A, resets self.mu to given mu
        """
        mu = np.asarray(mu)
        shape = mu.shape
        assert shape == (self._M, self._d), "`mu` must be of size (M,d)"
        self.mu = mu

    def reset_Sigma(self, Sigma):
        """
        Resets sigma.

        Parameters
        ----------
        Sigma : covariance for the M components,
                should be of shape [M, d]

        Returns
        -------
        N/A, resets self.Sigma to given Sigma
        """
        Sigma = np.asarray(Sigma)
        shape = Sigma.shape
        assert shape == (self._M, self._d), "`Sigma` must be of size (M,d)"
        self.Sigma = Sigma


def log_b_m_x(x, myTheta, m=None):
    """
    Returns the log probability of d-dimensional vector x using only
        component m of model myTheta (See equation 1 of the handout)

    As you'll see in tutorial, for efficiency, you can precompute
    something for 'm' that applies to all x outside of this function.
    Use `myTheta.preComputedForM(m)` for this.

    **IMPORTANT**: Return shape:
        (single row for specific m): if x.shape == [d] and m is not None, then
            return value is float (or equivalent)
        (single row for all m): if x.shape == [d] and m is None, then
            return shape is [M]
        (vectorized for all M) if x.shape == [T, d] and m is None, then
            return shape is [M, T]

    You should write your code such that it works for both types of inputs.
    But we encourage you to use the vectorized version in your `train`
    function for faster/efficient computation.

    Parameters
    ----------
    x : data, could either be a single vector of dimension d or a pack of T vectors
        which makes it of dimension [T, d]
    myTheta : parameters of class theta that we defined
    m : index of Gaussian, if m = None, you should handle it for all m in M

    Returns
    -------
    log_bmx : log probability of d-dimensional vector x (See equation 1 of the handout)
    """
    d = x.shape[-1]
    # Single Row for specific m (log_bmx in [1])
    if len(x.shape) == 1 and m != None:
        precomputed = myTheta.precomputedForM(m)
        diff = x - myTheta.mu[m]
        compute = -0.5 * np.sum((diff ** 2) / myTheta.Sigma[m])
        log_bmx = precomputed + compute
    # Single Row for all m (log_bmx in [M])
    elif len(x.shape) == 1:
        precomputed = np.array([myTheta.precomputedForM(i) for i in range(myTheta._M)])
        diff = x - myTheta.mu
        compute = -0.5 * np.sum((diff ** 2) / myTheta.Sigma, axis=-1)
        log_bmx = precomputed + compute
    # Vectorized (log_bmx in [M, T])
    else:
        precomputed = np.array([myTheta.precomputedForM(i) for i in range(myTheta._M)])
        diff = x[:, None, :] - myTheta.mu
        compute = -0.5 * np.sum((diff ** 2) / myTheta.Sigma, axis=-1)
        log_bmx = precomputed[:, None] + compute.T

    return log_bmx

def log_p_m_x(log_Bs, myTheta):
    """
    Returns the matrix of log probabilities i.e. log of p(m|X;theta)

    Specifically, each entry (m, t) in the output is the
        log probability of p(m|x_t; theta)

    For further information, See equation 2 of handout

    Return shape:
        same as log_Bs, np.ndarray of shape [M, T]

    NOTE: Log_Bs should be the vectorized version of log_bmx above

    Parameters
    ----------
    log_Bs : log probability of d-dimensional vector x (See equation 1 of the handout)
    myTheta : parameters of class theta that we defined

    Returns
    -------
    log_Ps : the matrix of log probabilities i.e. log of p(m|X;theta)
    """
    log_omega = np.log(myTheta.omega).reshape(-1, 1)
    log_numerator = log_omega + log_Bs

    # Sum in log space for all components
    log_denominator = np.logaddexp.reduce(log_numerator, axis=0)
    log_Ps = log_numerator - log_denominator

    return log_Ps

def logLik(log_Bs, myTheta):
    """
    Return the log likelihood of 'X' using model 'myTheta' and precomputed MxT matrix, 'log_Bs', of log_b_m_x

    X can be training data, when used in train( ... ), and
    X can be testing data, when used in test( ... ).

    We don't actually pass X directly to the function because we instead pass:

    log_Bs(m,t) is the log probability of vector x_t in component m, which is computed and stored outside of this function for efficiency.

    See equation 3 of the handout

    Parameters
    ----------
    log_Bs : log probability of d-dimensional vector x (See equation 1 of the handout)
    myTheta : parameters of class theta that we defined

    Returns
    -------
    log_Lik : the log likelihood (See equation 3 of the handout)
    """
    log_omega = np.log(myTheta.omega).reshape(-1, 1)
    log_likelihoods = np.logaddexp.reduce(log_omega + log_Bs, axis=0)
    log_lik = np.sum(log_likelihoods)

    return log_lik


def train(speaker, X, M=8, epsilon=0.0, maxIter=20):
    """ Train a model for the given speaker. Returns the theta (omega, mu, sigma)"""
    myTheta = theta(speaker, M, X.shape[1])
    # perform initialization
    T, d = X.shape  # Number of training samples (T) and dimensions (d)

    initial_omega = np.ones(M) / M
    myTheta.reset_omega(initial_omega)

    initial_mu = X[np.random.choice(T, M, replace=False), :]
    myTheta.reset_mu(initial_mu)

    initial_Sigma = np.var(X, axis=0) + 1e-6  # Add small value to avoid division by zero
    myTheta.reset_Sigma(np.tile(initial_Sigma, (M, 1)))

    prev_log_likelihood = -np.inf
    improvement = np.inf
    num_iter = 0

    while num_iter < maxIter and improvement > epsilon:
        log_Bs = log_b_m_x(X, myTheta)
        log_Ps = log_p_m_x(log_Bs, myTheta)

        responsibilities = np.exp(log_Ps) # [M,T]
        Nk = np.sum(responsibilities, axis=1)

        # Update omega (weights)
        new_omega = Nk / T
        myTheta.reset_omega(new_omega)

        # Update mu (means)
        weighted_sum_x = (responsibilities @ X) # X: [T,d]
        new_mu = weighted_sum_x / Nk[:, None]
        myTheta.reset_mu(new_mu)

        # Update Sigma (variances)
        weighted_sum_x2 = (responsibilities @ (X**2))
        new_Sigma = weighted_sum_x2 / Nk[:, None] - (new_mu ** 2)
        myTheta.reset_Sigma(new_Sigma)

        # Compute log likelihood
        log_likelihood = logLik(log_Bs, myTheta)

        # Update
        improvement = log_likelihood - prev_log_likelihood
        prev_log_likelihood = log_likelihood
        num_iter += 1

    return myTheta


def test(mfcc, correctID, models, k=5):
    """
    Computes the likelihood of 'mfcc' in each model in 'models', where the correct model is 'correctID'

    If k>0, print to stdout the actual speaker and the k best likelihoods in this format:
               [ACTUAL_ID]
               [SNAME1] [LOGLIK1]
               [SNAME2] [LOGLIK2]
               ...
               [SNAMEK] [LOGLIKK]

    e.g.,
               S-5A -9.21034037197
    the format of the log likelihood (number of decimal places, or exponent) does not matter
    """
    # bestModel = -1
    log_likelihoods = {}

    # Compute log likelihood for each model
    for model_idx, model in enumerate(models):
        log_Bs = log_b_m_x(mfcc, model)
        log_likelihood = logLik(log_Bs, model)
        log_likelihoods[model_idx] = log_likelihood

    # Sort the models by their log likelihood in descending order
    sorted_likelihoods = sorted(log_likelihoods.items(), key=lambda item: item[1], reverse=True)

    # Find the model with the highest likelihood
    bestModel = sorted_likelihoods[0][0]

    if k > 0:
        print(f"[{models[correctID].name}]")
        for i in range(min(k, len(sorted_likelihoods))):
            speaker_idx, likelihood = sorted_likelihoods[i]
            print(f"[{models[speaker_idx].name}] {likelihood}")

    return 1 if (bestModel == correctID) else 0


if __name__ == "__main__":

    trainThetas = []
    testMFCCs = []
    print("TODO: you will need to modify this main block for Sec 2.3")
    d = 13
    k = 5  # number of top speakers to display, <= 0 if none
    M = 3
    epsilon = -np.inf
    maxIter = 30
    # train a model for each speaker, and reserve data for testing

    # speakers_bar = 30

    for subdir, dirs, files in os.walk(dataDir):
        # number_of_speakers = 0
        for speaker in dirs:
            # number_of_speakers +=1
            # if number_of_speakers > speakers_bar:
            #     print("number of speakers:", number_of_speakers-1)
            #     break

            print(speaker)

            files = fnmatch.filter(os.listdir(os.path.join(dataDir, speaker)), "*npy")
            random.shuffle(files)

            testMFCC = np.load(os.path.join(dataDir, speaker, files.pop()))
            testMFCCs.append(testMFCC)

            X = np.empty((0, d))

            for file in files:
                myMFCC = np.load(os.path.join(dataDir, speaker, file))
                X = np.append(X, myMFCC, axis=0)

            trainThetas.append(train(speaker, X, M, epsilon, maxIter))

    # evaluate
    numCorrect = 0

    for i in range(0, len(testMFCCs)):
        numCorrect += test(testMFCCs[i], i, trainThetas, k)
    accuracy = 1.0 * numCorrect / len(testMFCCs)

    print(f"Accuracy = {accuracy}")
